### ISSUE TITLE
Unable to create a vagrant installation

### ISSUE THREAD

**Issue by party98** [fossasia/open-event-server#4680]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
While intializing the vagrant box, the pip fails to install `flask-rest-jsonapi from git+https://github.com/fossasia/flask-rest-jsonapi.git@shubhamp-master#egg=flask-rest-jsonapi (from -r requirements/common.txt` with the following message
```
    default: Obtaining flask-rest-jsonapi from git+https://github.com/fossasia/flask-rest-jsonapi.git@shubhamp-master#egg=flask-rest-jsonapi (from -r requirements/common.txt (line 46))
    default: Cleaning up...
    default: Cannot find command 'git'
    default: Storing debug log for failure in /root/.pip/pip.log
    default: Traceback (most recent call last):
    default:   File "create_db.py", line 7, in <module>
    default:     
    default: from builtins import input
    default: ImportError
    default: : 
    default: No module named builtins
```

**Expected behavior:**
The python requirements installation should get completed.

**Steps to reproduce:**
Follow the vagrant setup instructions.
